archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

builds:
  - binary: webrtc-log-parser
    id: chrome-webrtc-packet-log-parser
    goos:
      - darwin
      - windows
      - linux
      - freebsd
    goarch:
      - amd64
      - 386
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=readonly