name: Linters

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    name: golangci-lint
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run linter
        uses: actions-contrib/golangci-lint@v1